jekyll_models: [portfolio]
jekyll_models_generate_pages: true
jekyll_models_urls: rest-like
site_base: http://www.nicoleworthington.com/
#site_base: http://localhost:4000/
jekyll_sort:
  - src: portfolio
    by: order
    direction: down
    dest: portfolio